baseURL = "http://delonyang.github.io/"
languageCode = "zh-CN"
title = "Blog"
theme = "yinyang"
DefaultContentLanguage = "zh"

[author]
  name = "Delon Yang"
  homepage = "https://github.com/delonyang/"

# [languages]
#   [languages.cn]
#     contentDir = "content/cn"
#     languageName = "Chinese"
#     weight = 1

[params]
disqus = "joway" # disqus account name
extraHead = ''

[[params.socials]]
name = "About Me"
link = "https://joway.io"
[[params.socials]]
name = "Github"
link = "https://github.com/delonyang"
